extends Node

#intro section ---
var dialogMainFireSceneC0 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC0.tscn").instantiate()
var dialogMainFireSceneC1 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC1.tscn").instantiate()
var dialogMainFireSceneC2 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC2.tscn").instantiate()
var dialogMainFireSceneC3 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC3.tscn").instantiate()
var dialogMainFireSceneC4 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC4.tscn").instantiate()
var dialogMainFireSceneC5 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC5.tscn").instantiate()
var dialogMainFireSceneC6 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC6.tscn").instantiate()
var dialogMainFireSceneC7 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC7.tscn").instantiate()
var dialogMainFireSceneC8 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC8.tscn").instantiate()
var dialogMainFireSceneC9 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC9.tscn").instantiate()
var dialogMainFireSceneC10 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC10.tscn").instantiate()
var dialogMainFireSceneC11 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC11.tscn").instantiate()
var dialogMainFireSceneC12 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC12.tscn").instantiate()
var dialogMainFireSceneC13 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC13.tscn").instantiate()
var dialogMainFireSceneC14 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC14.tscn").instantiate()
var dialogMainFireSceneC15 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC15.tscn").instantiate()
var dialogMainFireSceneC16 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC16.tscn").instantiate()
var dialogMainFireSceneC17 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC17.tscn").instantiate()
var dialogMainFireSceneC18 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC18.tscn").instantiate()
var dialogMainFireSceneC19 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC19.tscn").instantiate()
var dialogMainFireSceneC20 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC20.tscn").instantiate()
var dialogMainFireSceneC21 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC21.tscn").instantiate()
var dialogMainFireSceneC22 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC22.tscn").instantiate()
var dialogMainFireSceneC23 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC23.tscn").instantiate()
var dialogMainFireSceneC24 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC24.tscn").instantiate()
var dialogMainFireSceneC25 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC25.tscn").instantiate()
var dialogMainFireSceneC26 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC26.tscn").instantiate()
var dialogMainFireSceneC27 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC27.tscn").instantiate()
var dialogMainFireSceneC28 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC28.tscn").instantiate()
var dialogMainFireSceneC29 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC29.tscn").instantiate()
var dialogMainFireSceneC30 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC30.tscn").instantiate()
var dialogMainFireSceneC31 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC31.tscn").instantiate()
var dialogMainFireSceneC32 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC32.tscn").instantiate()
var dialogMainFireSceneC33 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC33.tscn").instantiate()
var dialogMainFireSceneC34 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC34.tscn").instantiate()
var dialogMainFireSceneC35 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC35.tscn").instantiate()
var dialogMainFireSceneC36 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC36.tscn").instantiate()
var dialogMainFireSceneC37 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC37.tscn").instantiate()
var dialogMainFireSceneC38 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC38.tscn").instantiate()
var dialogMainFireSceneC39 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC39.tscn").instantiate()
var dialogMainFireSceneC40 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC40.tscn").instantiate()
var dialogMainFireSceneC41 = preload("res://Dialog/MainFireScene/DialogMainFireSceneC41.tscn").instantiate()

var mainFireScene = [
	dialogMainFireSceneC0,
	dialogMainFireSceneC1,
	dialogMainFireSceneC2,
	dialogMainFireSceneC3
]



#GirlTWarmer section ---
var dialogGirlTWarmerC0 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC0.tscn").instantiate()
var dialogGirlTWarmerC1 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC1.tscn").instantiate()
var dialogGirlTWarmerC2 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC2.tscn").instantiate()
var dialogGirlTWarmerC3 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC3.tscn").instantiate()
var dialogGirlTWarmerC4 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC4.tscn").instantiate()
var dialogGirlTWarmerC5 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC5.tscn").instantiate()
var dialogGirlTWarmerC6 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC6.tscn").instantiate()
var dialogGirlTWarmerC7 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC7.tscn").instantiate()
var dialogGirlTWarmerC8 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC8.tscn").instantiate()
var dialogGirlTWarmerC9 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC9.tscn").instantiate()
var dialogGirlTWarmerC10 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC10.tscn").instantiate()
var dialogGirlTWarmerC11 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC11.tscn").instantiate()
var dialogGirlTWarmerC12 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC12.tscn").instantiate()
var dialogGirlTWarmerC13 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC13.tscn").instantiate()
var dialogGirlTWarmerC14 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC14.tscn").instantiate()
var dialogGirlTWarmerC15 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC15.tscn").instantiate()
var dialogGirlTWarmerC16 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC16.tscn").instantiate()
var dialogGirlTWarmerC17 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC17.tscn").instantiate()
var dialogGirlTWarmerC18 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC18.tscn").instantiate()
var dialogGirlTWarmerC19 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC19.tscn").instantiate()
var dialogGirlTWarmerC20 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC20.tscn").instantiate()
var dialogGirlTWarmerC21 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC21.tscn").instantiate()
var dialogGirlTWarmerC22 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC22.tscn").instantiate()
var dialogGirlTWarmerC23 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC23.tscn").instantiate()
var dialogGirlTWarmerC24 = preload("res://Dialog/GirlTWarmer/DialogGirlTWarmerC24.tscn").instantiate()
